class Metrics:
    EPISODE_REWARD_MAX = 'episode_reward_max'
    EPISODE_REWARD_MIN = 'episode_reward_min'
    EPISODE_REWARD_MEAN = 'episode_reward_mean'
    EPISODE_LEN_MEAN = 'episode_len_mean'
    EPISODES_THIS_ITER = 'episodes_this_iter'
    NUM_HEALTHY_WORKERS = 'num_healthy_workers'
    TIMESTEPS_TOTAL = 'timesteps_total'
    TIMESTEPS_THIS_ITER = 'timesteps_this_iter'
    AGENT_TIMESTEPS_TOTAL = 'agent_timesteps_total'
    DONE = 'done'
    EPISODES_TOTAL = 'episodes_total'
    TRAINING_ITERATION = 'training_iteration'
    TRIAL_ID = 'trial_id'
    EXPERIMENT_ID = 'experiment_id'
    DATE = 'date'
    TIMESTAMP = 'timestamp'
    TIME_THIS_ITER_S = 'time_this_iter_s'
    TIME_TOTAL_S = 'time_total_s'
    PID = 'pid'
    HOSTNAME = 'hostname'
    NODE_IP = 'node_ip'
    TIME_SINCE_RESTORE = 'time_since_restore'
    TIMESTEPS_SINCE_RESTORE = 'timesteps_since_restore'
    ITERATIONS_SINCE_RESTORE = 'iterations_since_restore'
    CUSTOM_METRICSFINAL_TIME_MEAN = 'custom_metrics/final_time_mean'
    CUSTOM_METRICSFINAL_TIME_MIN = 'custom_metrics/final_time_min'
    CUSTOM_METRICSFINAL_TIME_MAX = 'custom_metrics/final_time_max'
    CUSTOM_METRICSFINAL_MASS_MEAN = 'custom_metrics/final_mass_mean'
    CUSTOM_METRICSFINAL_MASS_MIN = 'custom_metrics/final_mass_min'
    CUSTOM_METRICSFINAL_MASS_MAX = 'custom_metrics/final_mass_max'
    CUSTOM_METRICSFINAL_QUALITY_MEAN = 'custom_metrics/final_quality_mean'
    CUSTOM_METRICSFINAL_QUALITY_MIN = 'custom_metrics/final_quality_min'
    CUSTOM_METRICSFINAL_QUALITY_MAX = 'custom_metrics/final_quality_max'
    CUSTOM_METRICSFINAL_PLANTS_PER_M2_MEAN = 'custom_metrics/final_plants_per_m2_mean'
    CUSTOM_METRICSFINAL_PLANTS_PER_M2_MIN = 'custom_metrics/final_plants_per_m2_min'
    CUSTOM_METRICSFINAL_PLANTS_PER_M2_MAX = 'custom_metrics/final_plants_per_m2_max'
    CUSTOM_METRICSFINAL_AVERAGE_HEAD_PER_M2_MEAN = 'custom_metrics/final_average_head_per_m2_mean'
    CUSTOM_METRICSFINAL_AVERAGE_HEAD_PER_M2_MIN = 'custom_metrics/final_average_head_per_m2_min'
    CUSTOM_METRICSFINAL_AVERAGE_HEAD_PER_M2_MAX = 'custom_metrics/final_average_head_per_m2_max'
    CUSTOM_METRICSFINAL_GAINS_PLANT_MEAN = 'custom_metrics/final_gains_plant_mean'
    CUSTOM_METRICSFINAL_GAINS_PLANT_MIN = 'custom_metrics/final_gains_plant_min'
    CUSTOM_METRICSFINAL_GAINS_PLANT_MAX = 'custom_metrics/final_gains_plant_max'
    CUSTOM_METRICSFINAL_CUM_ELECTRICITY_USAGE_MEAN = 'custom_metrics/final_cum_electricity_usage_mean'
    CUSTOM_METRICSFINAL_CUM_ELECTRICITY_USAGE_MIN = 'custom_metrics/final_cum_electricity_usage_min'
    CUSTOM_METRICSFINAL_CUM_ELECTRICITY_USAGE_MAX = 'custom_metrics/final_cum_electricity_usage_max'
    CUSTOM_METRICSFINAL_CUM_HEAT_USAGE_MEAN = 'custom_metrics/final_cum_heat_usage_mean'
    CUSTOM_METRICSFINAL_CUM_HEAT_USAGE_MIN = 'custom_metrics/final_cum_heat_usage_min'
    CUSTOM_METRICSFINAL_CUM_HEAT_USAGE_MAX = 'custom_metrics/final_cum_heat_usage_max'
    CUSTOM_METRICSFINAL_CUM_CARBON_USAGE_MEAN = 'custom_metrics/final_cum_carbon_usage_mean'
    CUSTOM_METRICSFINAL_CUM_CARBON_USAGE_MIN = 'custom_metrics/final_cum_carbon_usage_min'
    CUSTOM_METRICSFINAL_CUM_CARBON_USAGE_MAX = 'custom_metrics/final_cum_carbon_usage_max'
    CUSTOM_METRICSFINAL_COSTS_VAR_ELECTRICITY_MEAN = 'custom_metrics/final_costs_var_electricity_mean'
    CUSTOM_METRICSFINAL_COSTS_VAR_ELECTRICITY_MIN = 'custom_metrics/final_costs_var_electricity_min'
    CUSTOM_METRICSFINAL_COSTS_VAR_ELECTRICITY_MAX = 'custom_metrics/final_costs_var_electricity_max'
    CUSTOM_METRICSFINAL_COSTS_VAR_HEAT_MEAN = 'custom_metrics/final_costs_var_heat_mean'
    CUSTOM_METRICSFINAL_COSTS_VAR_HEAT_MIN = 'custom_metrics/final_costs_var_heat_min'
    CUSTOM_METRICSFINAL_COSTS_VAR_HEAT_MAX = 'custom_metrics/final_costs_var_heat_max'
    CUSTOM_METRICSFINAL_COSTS_VAR_CARBON_MEAN = 'custom_metrics/final_costs_var_carbon_mean'
    CUSTOM_METRICSFINAL_COSTS_VAR_CARBON_MIN = 'custom_metrics/final_costs_var_carbon_min'
    CUSTOM_METRICSFINAL_COSTS_VAR_CARBON_MAX = 'custom_metrics/final_costs_var_carbon_max'
    CUSTOM_METRICSFINAL_COSTS_VAR_TOTAL_MEAN = 'custom_metrics/final_costs_var_total_mean'
    CUSTOM_METRICSFINAL_COSTS_VAR_TOTAL_MIN = 'custom_metrics/final_costs_var_total_min'
    CUSTOM_METRICSFINAL_COSTS_VAR_TOTAL_MAX = 'custom_metrics/final_costs_var_total_max'
    CUSTOM_METRICSFINAL_COSTS_FIX_TOTAL_MEAN = 'custom_metrics/final_costs_fix_total_mean'
    CUSTOM_METRICSFINAL_COSTS_FIX_TOTAL_MIN = 'custom_metrics/final_costs_fix_total_min'
    CUSTOM_METRICSFINAL_COSTS_FIX_TOTAL_MAX = 'custom_metrics/final_costs_fix_total_max'
    CUSTOM_METRICSFINAL_BALANCE_MEAN = 'custom_metrics/final_balance_mean'
    CUSTOM_METRICSFINAL_BALANCE_MIN = 'custom_metrics/final_balance_min'
    CUSTOM_METRICSFINAL_BALANCE_MAX = 'custom_metrics/final_balance_max'
    CUSTOM_METRICSTEMPERATURE_AIR_5_QUANTILE_MEAN = 'custom_metrics/temperature_air_5_quantile_mean'
    CUSTOM_METRICSTEMPERATURE_AIR_5_QUANTILE_MIN = 'custom_metrics/temperature_air_5_quantile_min'
    CUSTOM_METRICSTEMPERATURE_AIR_5_QUANTILE_MAX = 'custom_metrics/temperature_air_5_quantile_max'
    CUSTOM_METRICSTEMPERATURE_AIR_50_QUANTILE_MEAN = 'custom_metrics/temperature_air_50_quantile_mean'
    CUSTOM_METRICSTEMPERATURE_AIR_50_QUANTILE_MIN = 'custom_metrics/temperature_air_50_quantile_min'
    CUSTOM_METRICSTEMPERATURE_AIR_50_QUANTILE_MAX = 'custom_metrics/temperature_air_50_quantile_max'
    CUSTOM_METRICSTEMPERATURE_AIR_95_QUANTILE_MEAN = 'custom_metrics/temperature_air_95_quantile_mean'
    CUSTOM_METRICSTEMPERATURE_AIR_95_QUANTILE_MIN = 'custom_metrics/temperature_air_95_quantile_min'
    CUSTOM_METRICSTEMPERATURE_AIR_95_QUANTILE_MAX = 'custom_metrics/temperature_air_95_quantile_max'
    CUSTOM_METRICSPAR_LIGHT_5_QUANTILE_MEAN = 'custom_metrics/par_light_5_quantile_mean'
    CUSTOM_METRICSPAR_LIGHT_5_QUANTILE_MIN = 'custom_metrics/par_light_5_quantile_min'
    CUSTOM_METRICSPAR_LIGHT_5_QUANTILE_MAX = 'custom_metrics/par_light_5_quantile_max'
    CUSTOM_METRICSPAR_LIGHT_50_QUANTILE_MEAN = 'custom_metrics/par_light_50_quantile_mean'
    CUSTOM_METRICSPAR_LIGHT_50_QUANTILE_MIN = 'custom_metrics/par_light_50_quantile_min'
    CUSTOM_METRICSPAR_LIGHT_50_QUANTILE_MAX = 'custom_metrics/par_light_50_quantile_max'
    CUSTOM_METRICSPAR_LIGHT_95_QUANTILE_MEAN = 'custom_metrics/par_light_95_quantile_mean'
    CUSTOM_METRICSPAR_LIGHT_95_QUANTILE_MIN = 'custom_metrics/par_light_95_quantile_min'
    CUSTOM_METRICSPAR_LIGHT_95_QUANTILE_MAX = 'custom_metrics/par_light_95_quantile_max'
    CUSTOM_METRICSCARBON_PPM_5_QUANTILE_MEAN = 'custom_metrics/carbon_ppm_5_quantile_mean'
    CUSTOM_METRICSCARBON_PPM_5_QUANTILE_MIN = 'custom_metrics/carbon_ppm_5_quantile_min'
    CUSTOM_METRICSCARBON_PPM_5_QUANTILE_MAX = 'custom_metrics/carbon_ppm_5_quantile_max'
    CUSTOM_METRICSCARBON_PPM_50_QUANTILE_MEAN = 'custom_metrics/carbon_ppm_50_quantile_mean'
    CUSTOM_METRICSCARBON_PPM_50_QUANTILE_MIN = 'custom_metrics/carbon_ppm_50_quantile_min'
    CUSTOM_METRICSCARBON_PPM_50_QUANTILE_MAX = 'custom_metrics/carbon_ppm_50_quantile_max'
    CUSTOM_METRICSCARBON_PPM_95_QUANTILE_MEAN = 'custom_metrics/carbon_ppm_95_quantile_mean'
    CUSTOM_METRICSCARBON_PPM_95_QUANTILE_MIN = 'custom_metrics/carbon_ppm_95_quantile_min'
    CUSTOM_METRICSCARBON_PPM_95_QUANTILE_MAX = 'custom_metrics/carbon_ppm_95_quantile_max'
    CUSTOM_METRICSHEATER_POWER_ACTION_5_QUANTILE_MEAN = 'custom_metrics/heater_power_action_5_quantile_mean'
    CUSTOM_METRICSHEATER_POWER_ACTION_5_QUANTILE_MIN = 'custom_metrics/heater_power_action_5_quantile_min'
    CUSTOM_METRICSHEATER_POWER_ACTION_5_QUANTILE_MAX = 'custom_metrics/heater_power_action_5_quantile_max'
    CUSTOM_METRICSHEATER_POWER_ACTION_50_QUANTILE_MEAN = 'custom_metrics/heater_power_action_50_quantile_mean'
    CUSTOM_METRICSHEATER_POWER_ACTION_50_QUANTILE_MIN = 'custom_metrics/heater_power_action_50_quantile_min'
    CUSTOM_METRICSHEATER_POWER_ACTION_50_QUANTILE_MAX = 'custom_metrics/heater_power_action_50_quantile_max'
    CUSTOM_METRICSHEATER_POWER_ACTION_95_QUANTILE_MEAN = 'custom_metrics/heater_power_action_95_quantile_mean'
    CUSTOM_METRICSHEATER_POWER_ACTION_95_QUANTILE_MIN = 'custom_metrics/heater_power_action_95_quantile_min'
    CUSTOM_METRICSHEATER_POWER_ACTION_95_QUANTILE_MAX = 'custom_metrics/heater_power_action_95_quantile_max'
    CUSTOM_METRICSVENTILATION_POSITION_ACTION_5_QUANTILE_MEAN = 'custom_metrics/ventilation_position_action_5_quantile_mean'
    CUSTOM_METRICSVENTILATION_POSITION_ACTION_5_QUANTILE_MIN = 'custom_metrics/ventilation_position_action_5_quantile_min'
    CUSTOM_METRICSVENTILATION_POSITION_ACTION_5_QUANTILE_MAX = 'custom_metrics/ventilation_position_action_5_quantile_max'
    CUSTOM_METRICSVENTILATION_POSITION_ACTION_50_QUANTILE_MEAN = 'custom_metrics/ventilation_position_action_50_quantile_mean'
    CUSTOM_METRICSVENTILATION_POSITION_ACTION_50_QUANTILE_MIN = 'custom_metrics/ventilation_position_action_50_quantile_min'
    CUSTOM_METRICSVENTILATION_POSITION_ACTION_50_QUANTILE_MAX = 'custom_metrics/ventilation_position_action_50_quantile_max'
    CUSTOM_METRICSVENTILATION_POSITION_ACTION_95_QUANTILE_MEAN = 'custom_metrics/ventilation_position_action_95_quantile_mean'
    CUSTOM_METRICSVENTILATION_POSITION_ACTION_95_QUANTILE_MIN = 'custom_metrics/ventilation_position_action_95_quantile_min'
    CUSTOM_METRICSVENTILATION_POSITION_ACTION_95_QUANTILE_MAX = 'custom_metrics/ventilation_position_action_95_quantile_max'
    CUSTOM_METRICSCO2_FLOW_RATE_ACTION_5_QUANTILE_MEAN = 'custom_metrics/co2_flow_rate_action_5_quantile_mean'
    CUSTOM_METRICSCO2_FLOW_RATE_ACTION_5_QUANTILE_MIN = 'custom_metrics/co2_flow_rate_action_5_quantile_min'
    CUSTOM_METRICSCO2_FLOW_RATE_ACTION_5_QUANTILE_MAX = 'custom_metrics/co2_flow_rate_action_5_quantile_max'
    CUSTOM_METRICSCO2_FLOW_RATE_ACTION_50_QUANTILE_MEAN = 'custom_metrics/co2_flow_rate_action_50_quantile_mean'
    CUSTOM_METRICSCO2_FLOW_RATE_ACTION_50_QUANTILE_MIN = 'custom_metrics/co2_flow_rate_action_50_quantile_min'
    CUSTOM_METRICSCO2_FLOW_RATE_ACTION_50_QUANTILE_MAX = 'custom_metrics/co2_flow_rate_action_50_quantile_max'
    CUSTOM_METRICSCO2_FLOW_RATE_ACTION_95_QUANTILE_MEAN = 'custom_metrics/co2_flow_rate_action_95_quantile_mean'
    CUSTOM_METRICSCO2_FLOW_RATE_ACTION_95_QUANTILE_MIN = 'custom_metrics/co2_flow_rate_action_95_quantile_min'
    CUSTOM_METRICSCO2_FLOW_RATE_ACTION_95_QUANTILE_MAX = 'custom_metrics/co2_flow_rate_action_95_quantile_max'
    CUSTOM_METRICSSCREEN_BLACKOUT_POSITION_ACTION_5_QUANTILE_MEAN = 'custom_metrics/screen_blackout_position_action_5_quantile_mean'
    CUSTOM_METRICSSCREEN_BLACKOUT_POSITION_ACTION_5_QUANTILE_MIN = 'custom_metrics/screen_blackout_position_action_5_quantile_min'
    CUSTOM_METRICSSCREEN_BLACKOUT_POSITION_ACTION_5_QUANTILE_MAX = 'custom_metrics/screen_blackout_position_action_5_quantile_max'
    CUSTOM_METRICSSCREEN_BLACKOUT_POSITION_ACTION_50_QUANTILE_MEAN = 'custom_metrics/screen_blackout_position_action_50_quantile_mean'
    CUSTOM_METRICSSCREEN_BLACKOUT_POSITION_ACTION_50_QUANTILE_MIN = 'custom_metrics/screen_blackout_position_action_50_quantile_min'
    CUSTOM_METRICSSCREEN_BLACKOUT_POSITION_ACTION_50_QUANTILE_MAX = 'custom_metrics/screen_blackout_position_action_50_quantile_max'
    CUSTOM_METRICSSCREEN_BLACKOUT_POSITION_ACTION_95_QUANTILE_MEAN = 'custom_metrics/screen_blackout_position_action_95_quantile_mean'
    CUSTOM_METRICSSCREEN_BLACKOUT_POSITION_ACTION_95_QUANTILE_MIN = 'custom_metrics/screen_blackout_position_action_95_quantile_min'
    CUSTOM_METRICSSCREEN_BLACKOUT_POSITION_ACTION_95_QUANTILE_MAX = 'custom_metrics/screen_blackout_position_action_95_quantile_max'
    CUSTOM_METRICSSCREEN_TRANSPARENT_POSITION_ACTION_5_QUANTILE_MEAN = 'custom_metrics/screen_transparent_position_action_5_quantile_mean'
    CUSTOM_METRICSSCREEN_TRANSPARENT_POSITION_ACTION_5_QUANTILE_MIN = 'custom_metrics/screen_transparent_position_action_5_quantile_min'
    CUSTOM_METRICSSCREEN_TRANSPARENT_POSITION_ACTION_5_QUANTILE_MAX = 'custom_metrics/screen_transparent_position_action_5_quantile_max'
    CUSTOM_METRICSSCREEN_TRANSPARENT_POSITION_ACTION_50_QUANTILE_MEAN = 'custom_metrics/screen_transparent_position_action_50_quantile_mean'
    CUSTOM_METRICSSCREEN_TRANSPARENT_POSITION_ACTION_50_QUANTILE_MIN = 'custom_metrics/screen_transparent_position_action_50_quantile_min'
    CUSTOM_METRICSSCREEN_TRANSPARENT_POSITION_ACTION_50_QUANTILE_MAX = 'custom_metrics/screen_transparent_position_action_50_quantile_max'
    CUSTOM_METRICSSCREEN_TRANSPARENT_POSITION_ACTION_95_QUANTILE_MEAN = 'custom_metrics/screen_transparent_position_action_95_quantile_mean'
    CUSTOM_METRICSSCREEN_TRANSPARENT_POSITION_ACTION_95_QUANTILE_MIN = 'custom_metrics/screen_transparent_position_action_95_quantile_min'
    CUSTOM_METRICSSCREEN_TRANSPARENT_POSITION_ACTION_95_QUANTILE_MAX = 'custom_metrics/screen_transparent_position_action_95_quantile_max'
    CUSTOM_METRICSENABLE_LAMPS_ACTION_5_QUANTILE_MEAN = 'custom_metrics/enable_lamps_action_5_quantile_mean'
    CUSTOM_METRICSENABLE_LAMPS_ACTION_5_QUANTILE_MIN = 'custom_metrics/enable_lamps_action_5_quantile_min'
    CUSTOM_METRICSENABLE_LAMPS_ACTION_5_QUANTILE_MAX = 'custom_metrics/enable_lamps_action_5_quantile_max'
    CUSTOM_METRICSENABLE_LAMPS_ACTION_50_QUANTILE_MEAN = 'custom_metrics/enable_lamps_action_50_quantile_mean'
    CUSTOM_METRICSENABLE_LAMPS_ACTION_50_QUANTILE_MIN = 'custom_metrics/enable_lamps_action_50_quantile_min'
    CUSTOM_METRICSENABLE_LAMPS_ACTION_50_QUANTILE_MAX = 'custom_metrics/enable_lamps_action_50_quantile_max'
    CUSTOM_METRICSENABLE_LAMPS_ACTION_95_QUANTILE_MEAN = 'custom_metrics/enable_lamps_action_95_quantile_mean'
    CUSTOM_METRICSENABLE_LAMPS_ACTION_95_QUANTILE_MIN = 'custom_metrics/enable_lamps_action_95_quantile_min'
    CUSTOM_METRICSENABLE_LAMPS_ACTION_95_QUANTILE_MAX = 'custom_metrics/enable_lamps_action_95_quantile_max'
    HIST_STATSEPISODE_REWARD = 'hist_stats/episode_reward'
    HIST_STATSEPISODE_LENGTHS = 'hist_stats/episode_lengths'
    SAMPLER_PERFMEAN_RAW_OBS_PROCESSING_MS = 'sampler_perf/mean_raw_obs_processing_ms'
    SAMPLER_PERFMEAN_INFERENCE_MS = 'sampler_perf/mean_inference_ms'
    SAMPLER_PERFMEAN_ACTION_PROCESSING_MS = 'sampler_perf/mean_action_processing_ms'
    SAMPLER_PERFMEAN_ENV_WAIT_MS = 'sampler_perf/mean_env_wait_ms'
    SAMPLER_PERFMEAN_ENV_RENDER_MS = 'sampler_perf/mean_env_render_ms'
    TIMERSSAMPLE_TIME_MS = 'timers/sample_time_ms'
    TIMERSSAMPLE_THROUGHPUT = 'timers/sample_throughput'
    TIMERSLEARN_TIME_MS = 'timers/learn_time_ms'
    TIMERSLEARN_THROUGHPUT = 'timers/learn_throughput'
    TIMERSUPDATE_TIME_MS = 'timers/update_time_ms'
    INFONUM_STEPS_SAMPLED = 'info/num_steps_sampled'
    INFONUM_AGENT_STEPS_SAMPLED = 'info/num_agent_steps_sampled'
    INFONUM_STEPS_TRAINED = 'info/num_steps_trained'
    EVALUATIONEPISODE_REWARD_MAX = 'evaluation/episode_reward_max'
    EVALUATIONEPISODE_REWARD_MIN = 'evaluation/episode_reward_min'
    EVALUATIONEPISODE_REWARD_MEAN = 'evaluation/episode_reward_mean'
    EVALUATIONEPISODE_LEN_MEAN = 'evaluation/episode_len_mean'
    EVALUATIONEPISODES_THIS_ITER = 'evaluation/episodes_this_iter'
    PERFCPU_UTIL_PERCENT = 'perf/cpu_util_percent'
    PERFRAM_UTIL_PERCENT = 'perf/ram_util_percent'
    EVALUATIONCUSTOM_METRICSFINAL_TIME_MEAN = 'evaluation/custom_metrics/final_time_mean'
    EVALUATIONCUSTOM_METRICSFINAL_TIME_MIN = 'evaluation/custom_metrics/final_time_min'
    EVALUATIONCUSTOM_METRICSFINAL_TIME_MAX = 'evaluation/custom_metrics/final_time_max'
    EVALUATIONCUSTOM_METRICSFINAL_MASS_MEAN = 'evaluation/custom_metrics/final_mass_mean'
    EVALUATIONCUSTOM_METRICSFINAL_MASS_MIN = 'evaluation/custom_metrics/final_mass_min'
    EVALUATIONCUSTOM_METRICSFINAL_MASS_MAX = 'evaluation/custom_metrics/final_mass_max'
    EVALUATIONCUSTOM_METRICSFINAL_QUALITY_MEAN = 'evaluation/custom_metrics/final_quality_mean'
    EVALUATIONCUSTOM_METRICSFINAL_QUALITY_MIN = 'evaluation/custom_metrics/final_quality_min'
    EVALUATIONCUSTOM_METRICSFINAL_QUALITY_MAX = 'evaluation/custom_metrics/final_quality_max'
    EVALUATIONCUSTOM_METRICSFINAL_PLANTS_PER_M2_MEAN = 'evaluation/custom_metrics/final_plants_per_m2_mean'
    EVALUATIONCUSTOM_METRICSFINAL_PLANTS_PER_M2_MIN = 'evaluation/custom_metrics/final_plants_per_m2_min'
    EVALUATIONCUSTOM_METRICSFINAL_PLANTS_PER_M2_MAX = 'evaluation/custom_metrics/final_plants_per_m2_max'
    EVALUATIONCUSTOM_METRICSFINAL_AVERAGE_HEAD_PER_M2_MEAN = 'evaluation/custom_metrics/final_average_head_per_m2_mean'
    EVALUATIONCUSTOM_METRICSFINAL_AVERAGE_HEAD_PER_M2_MIN = 'evaluation/custom_metrics/final_average_head_per_m2_min'
    EVALUATIONCUSTOM_METRICSFINAL_AVERAGE_HEAD_PER_M2_MAX = 'evaluation/custom_metrics/final_average_head_per_m2_max'
    EVALUATIONCUSTOM_METRICSFINAL_GAINS_PLANT_MEAN = 'evaluation/custom_metrics/final_gains_plant_mean'
    EVALUATIONCUSTOM_METRICSFINAL_GAINS_PLANT_MIN = 'evaluation/custom_metrics/final_gains_plant_min'
    EVALUATIONCUSTOM_METRICSFINAL_GAINS_PLANT_MAX = 'evaluation/custom_metrics/final_gains_plant_max'
    EVALUATIONCUSTOM_METRICSFINAL_CUM_ELECTRICITY_USAGE_MEAN = 'evaluation/custom_metrics/final_cum_electricity_usage_mean'
    EVALUATIONCUSTOM_METRICSFINAL_CUM_ELECTRICITY_USAGE_MIN = 'evaluation/custom_metrics/final_cum_electricity_usage_min'
    EVALUATIONCUSTOM_METRICSFINAL_CUM_ELECTRICITY_USAGE_MAX = 'evaluation/custom_metrics/final_cum_electricity_usage_max'
    EVALUATIONCUSTOM_METRICSFINAL_CUM_HEAT_USAGE_MEAN = 'evaluation/custom_metrics/final_cum_heat_usage_mean'
    EVALUATIONCUSTOM_METRICSFINAL_CUM_HEAT_USAGE_MIN = 'evaluation/custom_metrics/final_cum_heat_usage_min'
    EVALUATIONCUSTOM_METRICSFINAL_CUM_HEAT_USAGE_MAX = 'evaluation/custom_metrics/final_cum_heat_usage_max'
    EVALUATIONCUSTOM_METRICSFINAL_CUM_CARBON_USAGE_MEAN = 'evaluation/custom_metrics/final_cum_carbon_usage_mean'
    EVALUATIONCUSTOM_METRICSFINAL_CUM_CARBON_USAGE_MIN = 'evaluation/custom_metrics/final_cum_carbon_usage_min'
    EVALUATIONCUSTOM_METRICSFINAL_CUM_CARBON_USAGE_MAX = 'evaluation/custom_metrics/final_cum_carbon_usage_max'
    EVALUATIONCUSTOM_METRICSFINAL_COSTS_VAR_ELECTRICITY_MEAN = 'evaluation/custom_metrics/final_costs_var_electricity_mean'
    EVALUATIONCUSTOM_METRICSFINAL_COSTS_VAR_ELECTRICITY_MIN = 'evaluation/custom_metrics/final_costs_var_electricity_min'
    EVALUATIONCUSTOM_METRICSFINAL_COSTS_VAR_ELECTRICITY_MAX = 'evaluation/custom_metrics/final_costs_var_electricity_max'
    EVALUATIONCUSTOM_METRICSFINAL_COSTS_VAR_HEAT_MEAN = 'evaluation/custom_metrics/final_costs_var_heat_mean'
    EVALUATIONCUSTOM_METRICSFINAL_COSTS_VAR_HEAT_MIN = 'evaluation/custom_metrics/final_costs_var_heat_min'
    EVALUATIONCUSTOM_METRICSFINAL_COSTS_VAR_HEAT_MAX = 'evaluation/custom_metrics/final_costs_var_heat_max'
    EVALUATIONCUSTOM_METRICSFINAL_COSTS_VAR_CARBON_MEAN = 'evaluation/custom_metrics/final_costs_var_carbon_mean'
    EVALUATIONCUSTOM_METRICSFINAL_COSTS_VAR_CARBON_MIN = 'evaluation/custom_metrics/final_costs_var_carbon_min'
    EVALUATIONCUSTOM_METRICSFINAL_COSTS_VAR_CARBON_MAX = 'evaluation/custom_metrics/final_costs_var_carbon_max'
    EVALUATIONCUSTOM_METRICSFINAL_COSTS_VAR_TOTAL_MEAN = 'evaluation/custom_metrics/final_costs_var_total_mean'
    EVALUATIONCUSTOM_METRICSFINAL_COSTS_VAR_TOTAL_MIN = 'evaluation/custom_metrics/final_costs_var_total_min'
    EVALUATIONCUSTOM_METRICSFINAL_COSTS_VAR_TOTAL_MAX = 'evaluation/custom_metrics/final_costs_var_total_max'
    EVALUATIONCUSTOM_METRICSFINAL_COSTS_FIX_TOTAL_MEAN = 'evaluation/custom_metrics/final_costs_fix_total_mean'
    EVALUATIONCUSTOM_METRICSFINAL_COSTS_FIX_TOTAL_MIN = 'evaluation/custom_metrics/final_costs_fix_total_min'
    EVALUATIONCUSTOM_METRICSFINAL_COSTS_FIX_TOTAL_MAX = 'evaluation/custom_metrics/final_costs_fix_total_max'
    EVALUATIONCUSTOM_METRICSFINAL_BALANCE_MEAN = 'evaluation/custom_metrics/final_balance_mean'
    EVALUATIONCUSTOM_METRICSFINAL_BALANCE_MIN = 'evaluation/custom_metrics/final_balance_min'
    EVALUATIONCUSTOM_METRICSFINAL_BALANCE_MAX = 'evaluation/custom_metrics/final_balance_max'
    EVALUATIONCUSTOM_METRICSTEMPERATURE_AIR_5_QUANTILE_MEAN = 'evaluation/custom_metrics/temperature_air_5_quantile_mean'
    EVALUATIONCUSTOM_METRICSTEMPERATURE_AIR_5_QUANTILE_MIN = 'evaluation/custom_metrics/temperature_air_5_quantile_min'
    EVALUATIONCUSTOM_METRICSTEMPERATURE_AIR_5_QUANTILE_MAX = 'evaluation/custom_metrics/temperature_air_5_quantile_max'
    EVALUATIONCUSTOM_METRICSTEMPERATURE_AIR_50_QUANTILE_MEAN = 'evaluation/custom_metrics/temperature_air_50_quantile_mean'
    EVALUATIONCUSTOM_METRICSTEMPERATURE_AIR_50_QUANTILE_MIN = 'evaluation/custom_metrics/temperature_air_50_quantile_min'
    EVALUATIONCUSTOM_METRICSTEMPERATURE_AIR_50_QUANTILE_MAX = 'evaluation/custom_metrics/temperature_air_50_quantile_max'
    EVALUATIONCUSTOM_METRICSTEMPERATURE_AIR_95_QUANTILE_MEAN = 'evaluation/custom_metrics/temperature_air_95_quantile_mean'
    EVALUATIONCUSTOM_METRICSTEMPERATURE_AIR_95_QUANTILE_MIN = 'evaluation/custom_metrics/temperature_air_95_quantile_min'
    EVALUATIONCUSTOM_METRICSTEMPERATURE_AIR_95_QUANTILE_MAX = 'evaluation/custom_metrics/temperature_air_95_quantile_max'
    EVALUATIONCUSTOM_METRICSPAR_LIGHT_5_QUANTILE_MEAN = 'evaluation/custom_metrics/par_light_5_quantile_mean'
    EVALUATIONCUSTOM_METRICSPAR_LIGHT_5_QUANTILE_MIN = 'evaluation/custom_metrics/par_light_5_quantile_min'
    EVALUATIONCUSTOM_METRICSPAR_LIGHT_5_QUANTILE_MAX = 'evaluation/custom_metrics/par_light_5_quantile_max'
    EVALUATIONCUSTOM_METRICSPAR_LIGHT_50_QUANTILE_MEAN = 'evaluation/custom_metrics/par_light_50_quantile_mean'
    EVALUATIONCUSTOM_METRICSPAR_LIGHT_50_QUANTILE_MIN = 'evaluation/custom_metrics/par_light_50_quantile_min'
    EVALUATIONCUSTOM_METRICSPAR_LIGHT_50_QUANTILE_MAX = 'evaluation/custom_metrics/par_light_50_quantile_max'
    EVALUATIONCUSTOM_METRICSPAR_LIGHT_95_QUANTILE_MEAN = 'evaluation/custom_metrics/par_light_95_quantile_mean'
    EVALUATIONCUSTOM_METRICSPAR_LIGHT_95_QUANTILE_MIN = 'evaluation/custom_metrics/par_light_95_quantile_min'
    EVALUATIONCUSTOM_METRICSPAR_LIGHT_95_QUANTILE_MAX = 'evaluation/custom_metrics/par_light_95_quantile_max'
    EVALUATIONCUSTOM_METRICSCARBON_PPM_5_QUANTILE_MEAN = 'evaluation/custom_metrics/carbon_ppm_5_quantile_mean'
    EVALUATIONCUSTOM_METRICSCARBON_PPM_5_QUANTILE_MIN = 'evaluation/custom_metrics/carbon_ppm_5_quantile_min'
    EVALUATIONCUSTOM_METRICSCARBON_PPM_5_QUANTILE_MAX = 'evaluation/custom_metrics/carbon_ppm_5_quantile_max'
    EVALUATIONCUSTOM_METRICSCARBON_PPM_50_QUANTILE_MEAN = 'evaluation/custom_metrics/carbon_ppm_50_quantile_mean'
    EVALUATIONCUSTOM_METRICSCARBON_PPM_50_QUANTILE_MIN = 'evaluation/custom_metrics/carbon_ppm_50_quantile_min'
    EVALUATIONCUSTOM_METRICSCARBON_PPM_50_QUANTILE_MAX = 'evaluation/custom_metrics/carbon_ppm_50_quantile_max'
    EVALUATIONCUSTOM_METRICSCARBON_PPM_95_QUANTILE_MEAN = 'evaluation/custom_metrics/carbon_ppm_95_quantile_mean'
    EVALUATIONCUSTOM_METRICSCARBON_PPM_95_QUANTILE_MIN = 'evaluation/custom_metrics/carbon_ppm_95_quantile_min'
    EVALUATIONCUSTOM_METRICSCARBON_PPM_95_QUANTILE_MAX = 'evaluation/custom_metrics/carbon_ppm_95_quantile_max'
    EVALUATIONCUSTOM_METRICSHEATER_POWER_ACTION_5_QUANTILE_MEAN = 'evaluation/custom_metrics/heater_power_action_5_quantile_mean'
    EVALUATIONCUSTOM_METRICSHEATER_POWER_ACTION_5_QUANTILE_MIN = 'evaluation/custom_metrics/heater_power_action_5_quantile_min'
    EVALUATIONCUSTOM_METRICSHEATER_POWER_ACTION_5_QUANTILE_MAX = 'evaluation/custom_metrics/heater_power_action_5_quantile_max'
    EVALUATIONCUSTOM_METRICSHEATER_POWER_ACTION_50_QUANTILE_MEAN = 'evaluation/custom_metrics/heater_power_action_50_quantile_mean'
    EVALUATIONCUSTOM_METRICSHEATER_POWER_ACTION_50_QUANTILE_MIN = 'evaluation/custom_metrics/heater_power_action_50_quantile_min'
    EVALUATIONCUSTOM_METRICSHEATER_POWER_ACTION_50_QUANTILE_MAX = 'evaluation/custom_metrics/heater_power_action_50_quantile_max'
    EVALUATIONCUSTOM_METRICSHEATER_POWER_ACTION_95_QUANTILE_MEAN = 'evaluation/custom_metrics/heater_power_action_95_quantile_mean'
    EVALUATIONCUSTOM_METRICSHEATER_POWER_ACTION_95_QUANTILE_MIN = 'evaluation/custom_metrics/heater_power_action_95_quantile_min'
    EVALUATIONCUSTOM_METRICSHEATER_POWER_ACTION_95_QUANTILE_MAX = 'evaluation/custom_metrics/heater_power_action_95_quantile_max'
    EVALUATIONCUSTOM_METRICSVENTILATION_POSITION_ACTION_5_QUANTILE_MEAN = 'evaluation/custom_metrics/ventilation_position_action_5_quantile_mean'
    EVALUATIONCUSTOM_METRICSVENTILATION_POSITION_ACTION_5_QUANTILE_MIN = 'evaluation/custom_metrics/ventilation_position_action_5_quantile_min'
    EVALUATIONCUSTOM_METRICSVENTILATION_POSITION_ACTION_5_QUANTILE_MAX = 'evaluation/custom_metrics/ventilation_position_action_5_quantile_max'
    EVALUATIONCUSTOM_METRICSVENTILATION_POSITION_ACTION_50_QUANTILE_MEAN = 'evaluation/custom_metrics/ventilation_position_action_50_quantile_mean'
    EVALUATIONCUSTOM_METRICSVENTILATION_POSITION_ACTION_50_QUANTILE_MIN = 'evaluation/custom_metrics/ventilation_position_action_50_quantile_min'
    EVALUATIONCUSTOM_METRICSVENTILATION_POSITION_ACTION_50_QUANTILE_MAX = 'evaluation/custom_metrics/ventilation_position_action_50_quantile_max'
    EVALUATIONCUSTOM_METRICSVENTILATION_POSITION_ACTION_95_QUANTILE_MEAN = 'evaluation/custom_metrics/ventilation_position_action_95_quantile_mean'
    EVALUATIONCUSTOM_METRICSVENTILATION_POSITION_ACTION_95_QUANTILE_MIN = 'evaluation/custom_metrics/ventilation_position_action_95_quantile_min'
    EVALUATIONCUSTOM_METRICSVENTILATION_POSITION_ACTION_95_QUANTILE_MAX = 'evaluation/custom_metrics/ventilation_position_action_95_quantile_max'
    EVALUATIONCUSTOM_METRICSCO2_FLOW_RATE_ACTION_5_QUANTILE_MEAN = 'evaluation/custom_metrics/co2_flow_rate_action_5_quantile_mean'
    EVALUATIONCUSTOM_METRICSCO2_FLOW_RATE_ACTION_5_QUANTILE_MIN = 'evaluation/custom_metrics/co2_flow_rate_action_5_quantile_min'
    EVALUATIONCUSTOM_METRICSCO2_FLOW_RATE_ACTION_5_QUANTILE_MAX = 'evaluation/custom_metrics/co2_flow_rate_action_5_quantile_max'
    EVALUATIONCUSTOM_METRICSCO2_FLOW_RATE_ACTION_50_QUANTILE_MEAN = 'evaluation/custom_metrics/co2_flow_rate_action_50_quantile_mean'
    EVALUATIONCUSTOM_METRICSCO2_FLOW_RATE_ACTION_50_QUANTILE_MIN = 'evaluation/custom_metrics/co2_flow_rate_action_50_quantile_min'
    EVALUATIONCUSTOM_METRICSCO2_FLOW_RATE_ACTION_50_QUANTILE_MAX = 'evaluation/custom_metrics/co2_flow_rate_action_50_quantile_max'
    EVALUATIONCUSTOM_METRICSCO2_FLOW_RATE_ACTION_95_QUANTILE_MEAN = 'evaluation/custom_metrics/co2_flow_rate_action_95_quantile_mean'
    EVALUATIONCUSTOM_METRICSCO2_FLOW_RATE_ACTION_95_QUANTILE_MIN = 'evaluation/custom_metrics/co2_flow_rate_action_95_quantile_min'
    EVALUATIONCUSTOM_METRICSCO2_FLOW_RATE_ACTION_95_QUANTILE_MAX = 'evaluation/custom_metrics/co2_flow_rate_action_95_quantile_max'
    EVALUATIONCUSTOM_METRICSSCREEN_BLACKOUT_POSITION_ACTION_5_QUANTILE_MEAN = 'evaluation/custom_metrics/screen_blackout_position_action_5_quantile_mean'
    EVALUATIONCUSTOM_METRICSSCREEN_BLACKOUT_POSITION_ACTION_5_QUANTILE_MIN = 'evaluation/custom_metrics/screen_blackout_position_action_5_quantile_min'
    EVALUATIONCUSTOM_METRICSSCREEN_BLACKOUT_POSITION_ACTION_5_QUANTILE_MAX = 'evaluation/custom_metrics/screen_blackout_position_action_5_quantile_max'
    EVALUATIONCUSTOM_METRICSSCREEN_BLACKOUT_POSITION_ACTION_50_QUANTILE_MEAN = 'evaluation/custom_metrics/screen_blackout_position_action_50_quantile_mean'
    EVALUATIONCUSTOM_METRICSSCREEN_BLACKOUT_POSITION_ACTION_50_QUANTILE_MIN = 'evaluation/custom_metrics/screen_blackout_position_action_50_quantile_min'
    EVALUATIONCUSTOM_METRICSSCREEN_BLACKOUT_POSITION_ACTION_50_QUANTILE_MAX = 'evaluation/custom_metrics/screen_blackout_position_action_50_quantile_max'
    EVALUATIONCUSTOM_METRICSSCREEN_BLACKOUT_POSITION_ACTION_95_QUANTILE_MEAN = 'evaluation/custom_metrics/screen_blackout_position_action_95_quantile_mean'
    EVALUATIONCUSTOM_METRICSSCREEN_BLACKOUT_POSITION_ACTION_95_QUANTILE_MIN = 'evaluation/custom_metrics/screen_blackout_position_action_95_quantile_min'
    EVALUATIONCUSTOM_METRICSSCREEN_BLACKOUT_POSITION_ACTION_95_QUANTILE_MAX = 'evaluation/custom_metrics/screen_blackout_position_action_95_quantile_max'
    EVALUATIONCUSTOM_METRICSSCREEN_TRANSPARENT_POSITION_ACTION_5_QUANTILE_MEAN = 'evaluation/custom_metrics/screen_transparent_position_action_5_quantile_mean'
    EVALUATIONCUSTOM_METRICSSCREEN_TRANSPARENT_POSITION_ACTION_5_QUANTILE_MIN = 'evaluation/custom_metrics/screen_transparent_position_action_5_quantile_min'
    EVALUATIONCUSTOM_METRICSSCREEN_TRANSPARENT_POSITION_ACTION_5_QUANTILE_MAX = 'evaluation/custom_metrics/screen_transparent_position_action_5_quantile_max'
    EVALUATIONCUSTOM_METRICSSCREEN_TRANSPARENT_POSITION_ACTION_50_QUANTILE_MEAN = 'evaluation/custom_metrics/screen_transparent_position_action_50_quantile_mean'
    EVALUATIONCUSTOM_METRICSSCREEN_TRANSPARENT_POSITION_ACTION_50_QUANTILE_MIN = 'evaluation/custom_metrics/screen_transparent_position_action_50_quantile_min'
    EVALUATIONCUSTOM_METRICSSCREEN_TRANSPARENT_POSITION_ACTION_50_QUANTILE_MAX = 'evaluation/custom_metrics/screen_transparent_position_action_50_quantile_max'
    EVALUATIONCUSTOM_METRICSSCREEN_TRANSPARENT_POSITION_ACTION_95_QUANTILE_MEAN = 'evaluation/custom_metrics/screen_transparent_position_action_95_quantile_mean'
    EVALUATIONCUSTOM_METRICSSCREEN_TRANSPARENT_POSITION_ACTION_95_QUANTILE_MIN = 'evaluation/custom_metrics/screen_transparent_position_action_95_quantile_min'
    EVALUATIONCUSTOM_METRICSSCREEN_TRANSPARENT_POSITION_ACTION_95_QUANTILE_MAX = 'evaluation/custom_metrics/screen_transparent_position_action_95_quantile_max'
    EVALUATIONCUSTOM_METRICSENABLE_LAMPS_ACTION_5_QUANTILE_MEAN = 'evaluation/custom_metrics/enable_lamps_action_5_quantile_mean'
    EVALUATIONCUSTOM_METRICSENABLE_LAMPS_ACTION_5_QUANTILE_MIN = 'evaluation/custom_metrics/enable_lamps_action_5_quantile_min'
    EVALUATIONCUSTOM_METRICSENABLE_LAMPS_ACTION_5_QUANTILE_MAX = 'evaluation/custom_metrics/enable_lamps_action_5_quantile_max'
    EVALUATIONCUSTOM_METRICSENABLE_LAMPS_ACTION_50_QUANTILE_MEAN = 'evaluation/custom_metrics/enable_lamps_action_50_quantile_mean'
    EVALUATIONCUSTOM_METRICSENABLE_LAMPS_ACTION_50_QUANTILE_MIN = 'evaluation/custom_metrics/enable_lamps_action_50_quantile_min'
    EVALUATIONCUSTOM_METRICSENABLE_LAMPS_ACTION_50_QUANTILE_MAX = 'evaluation/custom_metrics/enable_lamps_action_50_quantile_max'
    EVALUATIONCUSTOM_METRICSENABLE_LAMPS_ACTION_95_QUANTILE_MEAN = 'evaluation/custom_metrics/enable_lamps_action_95_quantile_mean'
    EVALUATIONCUSTOM_METRICSENABLE_LAMPS_ACTION_95_QUANTILE_MIN = 'evaluation/custom_metrics/enable_lamps_action_95_quantile_min'
    EVALUATIONCUSTOM_METRICSENABLE_LAMPS_ACTION_95_QUANTILE_MAX = 'evaluation/custom_metrics/enable_lamps_action_95_quantile_max'
    EVALUATIONHIST_STATSEPISODE_REWARD = 'evaluation/hist_stats/episode_reward'
    EVALUATIONHIST_STATSEPISODE_LENGTHS = 'evaluation/hist_stats/episode_lengths'
    EVALUATIONSAMPLER_PERFMEAN_RAW_OBS_PROCESSING_MS = 'evaluation/sampler_perf/mean_raw_obs_processing_ms'
    EVALUATIONSAMPLER_PERFMEAN_INFERENCE_MS = 'evaluation/sampler_perf/mean_inference_ms'
    EVALUATIONSAMPLER_PERFMEAN_ACTION_PROCESSING_MS = 'evaluation/sampler_perf/mean_action_processing_ms'
    EVALUATIONSAMPLER_PERFMEAN_ENV_WAIT_MS = 'evaluation/sampler_perf/mean_env_wait_ms'
    EVALUATIONSAMPLER_PERFMEAN_ENV_RENDER_MS = 'evaluation/sampler_perf/mean_env_render_ms'
    INFOLEARNERDEFAULT_POLICYLEARNER_STATSCUR_KL_COEFF = 'info/learner/default_policy/learner_stats/cur_kl_coeff'
    INFOLEARNERDEFAULT_POLICYLEARNER_STATSCUR_LR = 'info/learner/default_policy/learner_stats/cur_lr'
    INFOLEARNERDEFAULT_POLICYLEARNER_STATSTOTAL_LOSS = 'info/learner/default_policy/learner_stats/total_loss'
    INFOLEARNERDEFAULT_POLICYLEARNER_STATSPOLICY_LOSS = 'info/learner/default_policy/learner_stats/policy_loss'
    INFOLEARNERDEFAULT_POLICYLEARNER_STATSVF_LOSS = 'info/learner/default_policy/learner_stats/vf_loss'
    INFOLEARNERDEFAULT_POLICYLEARNER_STATSVF_EXPLAINED_VAR = 'info/learner/default_policy/learner_stats/vf_explained_var'
    INFOLEARNERDEFAULT_POLICYLEARNER_STATSKL = 'info/learner/default_policy/learner_stats/kl'
    INFOLEARNERDEFAULT_POLICYLEARNER_STATSENTROPY = 'info/learner/default_policy/learner_stats/entropy'
    INFOLEARNERDEFAULT_POLICYLEARNER_STATSENTROPY_COEFF = 'info/learner/default_policy/learner_stats/entropy_coeff'

    # SAC specific ones.
    INFOLEARNERDEFAULT_POLICYLEARNER_STATSACTOR_LOSS = 'info/learner/default_policy/learner_stats/actor_loss'
    INFOLEARNERDEFAULT_POLICYLEARNER_STATSCRITIC_LOSS = 'info/learner/default_policy/learner_stats/critic_loss'
    INFOLEARNERDEFAULT_POLICYLEARNER_STATSALPHA_LOSS = 'info/learner/default_policy/learner_stats/alpha_loss'

    @staticmethod
    def map_to_normal_name(column: str) -> str:
        """Returns only the last part of the column, capitalized and looking fancy."""
        is_custom = 'custom_metrics' in column
        if '_max' in column or '_min' in column:
            raise AssertionError("Assumed to use only quantile mean")

        # Magical string processing two-liner.
        if is_custom:
            return " ".join([word.capitalize() for word in column.split("/")[-1].split("_")[:-1]])
        return " ".join([word.capitalize() for word in column.split("/")[-1].split("_")])

    @staticmethod
    def map_to_label_with_unit(column: str) -> str:
        return MAP_COL_TO_LABEL_WITH_UNIT[column]


MAP_COL_TO_LABEL_WITH_UNIT = {
    Metrics.INFOLEARNERDEFAULT_POLICYLEARNER_STATSPOLICY_LOSS: "Policy Loss [-]",
    Metrics.INFOLEARNERDEFAULT_POLICYLEARNER_STATSVF_LOSS: "VF Loss [-]",
    Metrics.INFOLEARNERDEFAULT_POLICYLEARNER_STATSTOTAL_LOSS: "Total Loss [-]",
    Metrics.INFOLEARNERDEFAULT_POLICYLEARNER_STATSACTOR_LOSS: "Actor Loss [-]",
    Metrics.INFOLEARNERDEFAULT_POLICYLEARNER_STATSCRITIC_LOSS: "Critic Loss [-]",
    Metrics.INFOLEARNERDEFAULT_POLICYLEARNER_STATSALPHA_LOSS: "Alpha Loss [-]",
    Metrics.EPISODE_REWARD_MEAN: "Reward Mean [-]",

    Metrics.CUSTOM_METRICSFINAL_BALANCE_MEAN: "Final Balance [€/m²]",
    Metrics.EVALUATIONCUSTOM_METRICSFINAL_BALANCE_MEAN: "Eval Final Balance [€/m²]",
    Metrics.EVALUATIONCUSTOM_METRICSFINAL_MASS_MEAN: "Final Mass [g]",
    Metrics.EVALUATIONCUSTOM_METRICSFINAL_QUALITY_MEAN: "Final Quality [-]",
    Metrics.TIMESTEPS_TOTAL: 'Total Time Steps [-]',
    'evaluation/custom_metrics/temperature_air': "Temperature Air [K]",
    'evaluation/custom_metrics/par_light': "PAR [µmol/m²s]",
    'evaluation/custom_metrics/carbon_ppm': "Carbon PPMv [-]",
}
